  name: install php
  on: workflow_dispatch
  jobs:
      job1: install php
      runs_on: ubuntu-latest
      steps:
      - name: install
        run: |
          sudo apt update
          sudo apt install php -y
          php --version
